version: '3.8'

services:
  app:
    ports:
      - "3000:3004"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:password@db:5432/mydatabase
    command: npm start # Regular start command for production

  db:
    ports:
      - "5432:5432"
