version: '3.8'

services:
  nginx:
    ports:
      - "3004:80"
  app:
    build: 
      context: .
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:password@db:5432/mydatabase
    command: npm start # Regular start command for production

  db:
    ports:
      - "5432:5432"
